# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'product_types',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 16, 33, 36, 8095, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='product_type',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
