# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160318_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 18, 16, 54, 27, 649930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_delete',
            field=models.DateTimeField(null=True),
        ),
    ]
