# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20160318_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
