# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20160323_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(default='image', max_length=200),
        ),
    ]
