# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20160320_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comments_from',
            new_name='user_from',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comments_date',
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
