# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.TextField()),
                ('main_title', models.TextField()),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
